# my global config
global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'search_client_2'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.52:8101']
  
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'shop_client_2'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.52:8102']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'web_client_2'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.52:8103']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'media_client_2'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.52:8104']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'search_client_3'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.53:8101']
  
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'shop_client_3'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.53:8102']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'web_client_3'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.53:8103']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'media_client_3'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.53:8104']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'search_client_4'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.54:8101']
  
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'shop_client_4'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.54:8102']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'web_client_4'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.54:8103']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'media_client_4'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.54:8104']


# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'search_server_2'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.52:9101']
  
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'shop_server_2'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.52:9102']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'web_server_2'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.52:9103']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'media_server_2'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.52:9104']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'search_server_3'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.53:9101']
  
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'shop_server_3'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.53:9102']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'web_server_3'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.53:9103']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'media_server_3'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.53:9104']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'search_server_4'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.54:9101']
  
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'shop_server_4'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.54:9102']

# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'web_server_4'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.54:9103']


# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'media_server_4'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['131.155.35.54:9104']